<?php

// Sub categories for Toys & Hobbies
$men_clothing_and_accessories = [
    'Belts',
    'Eyewear',
    'Gloves & Mittens',
    'Hats & Caps',
    'Hoodies & Sweatshirts',
    'Jackets & Coats',
    'Jeans',
    'Men\'s Sleep & Lounge',
    'Pants',
    'Scarves & Wraps',
    'Shirts',
    'Shorts',
    'Socks',
    'Suits & Blazers',
    'Sweaters',
    'Swimwear',
    'Tops & Tees',
    'Underwear',
];
$women_clothing_and_accessories = [
    'Blouses & Shirts',
    'Bodysuits',
    'Bottoms',
    'Dresses',
    'Hoodies & Sweatshirts',
    'Intimates',
    'Jackets & Coats',
    'Leggings',
    'Sleep & Lounge',
    'Socks & Hosiery',
    'Suits & Sets',
    'Sweaters',
    'Tops & Tees',
];
$toys = [
    'Action & Toy Figures',
    'Baby Toys',
    'Classic Toys',
    'Diecasts & Toy Vehicles',
    'Dolls & Stuffed Toys',
    'Electronic Toys',
    'Learning & Education',
    'Models & Building Toy',
    'Novelty & Gag Toys',
    'Outdoor Fun & Sports',
    'Puzzles & Magic Cubes',
    'Remote Control Toys',
];
$Beauty_Health = [
    'Bath & Shower',
    'Beauty Essentials',
    'Fragrances & Deodorants',
    'Hair Care & Styling',
    'Hair Extensions & Wigs',
    'Health Care',
    'Human Hair',
    'Makeup',
    'Nails & Tools',
    'Oral Hygiene',
    'Sanitary Paper',
    'Sex Products',
    'Shaving & Hair Removal',
    'Skin Care',
    'Tattoo & Body Art',
    'Tools & Accessories',
];
$Jewelry_Accessories = [
    'Beads & Jewelry Making',
    'Bracelets & Bangles',
    'Earrings',
    'Fine Jewelry',
    'Jewelry Sets & More',
    'Necklaces & Pendants',
    'Rings',
    'Wedding & Engagement Jewelry',
];
$Home_Garden = [

    'Arts, Crafts & Sewing',
    'Bathroom Products',
    'Festive & Party Supplies',
    'Garden Supplies',
    'Home Decor',
    'Home Storage & Organization',
    'Home Textile',
    'Household Merchandises',
    'Housekeeping & Organization',
    'Kitchen,Dining & Bar',
    'Pet Products',
    'Umbrellas & Rain Accessories',

];
$Mother_Kids = [
    'Activity & Gear',
    'Baby Bedding',
    'Baby Boys Clothing',
    'Baby Care',
    'Baby Shoes',
    'Boys Clothing',
    'Children\'s Shoes',
    'Family Matching Outfits',
    'Feeding',
    'Pregnancy & Maternity',
    'Safety',
];
$Watches = [
    'Children\'s Watches',
    'Lover\'s Watches',
    'Men\'s Watches',
    'Pocket & Fob Watches',
    'Watch Accessories',
    'Women\'s Bracelet Watches',
    'Women\'s Watches',
];
$Sports_Entertainment = [

    'Bowling',
    'Camping & Hiking',
    'Cycling',
    'Entertainment',
    'Fishing',
    'Fitness & Body Building',
    'Golf',
    'Horse Racing',
    'Hunting',
    'Musical Instruments',
    'Racquet Sports',
    'Roller, Skate board & Scooters',
    'Running',
    'Shooting',
    'Skiing & Snowboarding',
    'Sneakers',
    'Sport Accessories',
    'Sports Bags',
    'Sports Clothing',
    'Swimming',
    'Team Sports',
    'Water Sports',
];
$Automobiles_Motorcycles = [
    'Auto Replacement Parts',
    'Car Electronics',
    'Car Lights',
    'Exterior Accessories',
    'Interior Accessories',
    'Motorcycle Accessories & Parts',
    'Other Vehicle Parts & Accessories',
    'Roadway Safety',
    'Tools, Maintenance & Care',
];
$Computer_Office = [
    'Cables & Connectors',
    'Computer Components',
    'Computer Peripherals',
    'DIY Computers',
    'Demo Board',
    'Desktops & Servers',
    'Laptop Accessories',
    'Laptops',
    'Memory Cards & Accessories',
    'Mini PCs',
    'Networking',
    'Office Electronics',
    'Other Computer Products',
    'Software',
    'Storage Devices',
    'Tablet Accessories',
    'Tablet PCs',
];
$Electronic_Components_Supplies = [
    'Active Components',
    'EL Products',
    'Electronic Accessories & Supplies',
    'Electronic Data Systems',
    'Electronic Signs',
    'Electronics Production Machinery',
    'Electronics Stocks',
    'Optoelectronic Displays',
    'Passive Components',
];
$Furniture = [
    'Bar Furniture',
    'Children Furniture',
    'Commercial Furniture',
    'Furniture Accessories',
    'Furniture Hardware',
    'Furniture Parts',
    'Home Furniture',
    'Office Furniture',
    'Outdoor Furniture',
];
$Home_Improvement = [
    'Bathroom Fixtures',
    'Building Supplies',
    'Electrical Equipment & Supplies',
    'Hardware',
    'Home Appliances',
    'Household Appliances',
    'Kitchen Fixtures',
    'Security & Protection',
    'Tools',
];
$Lights_Lighting = [
    'Book Lights',
    'Ceiling Lights & Fans',
    'Commercial Lighting',
    'Holiday Lighting',
    'LED Lamps',
    'LED Lighting',
    'Lamps & Shades',
    'Light Bulbs',
    'Lighting Accessories',
    'Night Lights',
    'Novelty Lighting',
    'Outdoor Lighting',
    'Portable Lighting',
    'Professional Lighting',
];

?>
